import"./assets/styles-COSbD4d6.js";import{a as i}from"./assets/vendor-B1ZHW564.js";const S="https://dummyjson.com",l={CATEGORIES:"/products/category-list",PRODUCTS:"/products",CATEGORY:"/products/category/"},d=12;i.defaults.baseURL=S;async function C(){const{data:t}=await i.get(l.CATEGORIES);return t}async function u(t){const e=(t-1)*12,{data:o}=await i.get(`${l.PRODUCTS}?limit=${d}&skip=${e}`);return o}async function q(t,e){const o=(e-1)*12,{data:c}=await i.get(`${l.CATEGORY}${t}?limit=${d}&skip=${o}`);return c}const s={listCategories:document.querySelector(".categories"),listProducts:document.querySelector(".products"),loadMore:document.querySelector(".load-more-btn"),loader:document.querySelector(".loader"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),form:document.querySelector(".search-form"),formClearBtn:document.querySelector(".search-form__btn-clear"),notFound:document.querySelector(".not-found"),modalAddToCart:document.querySelector(".modal-product__btn--cart"),modalWishlistCart:document.querySelector(".modal-product__btn--wishlist")};function P(t){const e=t.map(o=>`
<li class="categories__item">
   <button class="categories__btn" type="button">${o}</button>
 </li>
`).join("");s.listCategories.innerHTML=e}function m(t){const e=t.map(({id:o,category:c,thumbnail:r,title:a,brand:L,price:b})=>`
    <li class="products__item" data-id="${o}">
    <img class="products__image" src="${r}" alt="${a}"/>
    <p class="products__title">${a}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${L}</span></p>
    <p class="products__category">Category: ${c}</p>
    <p class="products__price">Price: ${b}</p>
 </li>
`).join("");s.listProducts.insertAdjacentHTML("beforeend",e)}function p(){s.loadMore.classList.remove("is-hidden")}function g(){s.loadMore.classList.remove("is-hidden")}function _(){s.loader.classList.add("is-hidden")}function f(){s.loader.classList.add("is-hidden")}function $(){s.listProducts.innerHTML=""}function y(){s.notFound.classList.add("not-found--visible")}function h(){s.notFound.classList.remove("not-found--visible")}let n=1;async function A(){try{h(),g(),_();const t=await C();console.log(t);const e=["All",...t];P(e),document.querySelector(".categories__btn").classList.add("categories__btn--active");const{products:o,total:c,skip:r}=await u(n);o.length>0?(m(o),c-r-d>0&&p()):y()}catch(t){console.log(t)}finally{f()}}async function E(t){if(t.target.nodeName!=="BUTTON")return;const e=t.target.textContent;document.querySelectorAll(".categories__btn").forEach(o=>{o.classList.remove("categories__btn--active")}),t.target.classList.add("categories__btn--active");try{h(),g(),_(),$(),console.log(e),n=1;let o;const{products:c,total:r,skip:a}=e==="All"?await u(n):await q(e,n);c.length>0?(m(c),r-a-d>0&&p()):y()}catch(o){console.log(o.message)}finally{f()}}document.addEventListener("DOMContentLoaded",A);s.listCategories.addEventListener("click",E);
//# sourceMappingURL=index.js.map
