import"./assets/styles-COSbD4d6.js";import{a as d}from"./assets/vendor-B1ZHW564.js";const T="https://dummyjson.com",i={CATEGORIES:"/products/category-list",PRODUCTS:"/products",CATEGORY:"/products/category/",PRODUCT_BY_ID:"/products/",SEARCH_PRODUCT:"/products/search"},l=12,a={listCategories:document.querySelector(".categories"),listProducts:document.querySelector(".products"),loadMore:document.querySelector(".load-more-btn"),loader:document.querySelector(".loader"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),form:document.querySelector(".search-form"),formClearBtn:document.querySelector(".search-form__btn-clear"),notFound:document.querySelector(".not-found"),modalAddToCart:document.querySelector(".modal-product__btn--cart"),modalWishlistCart:document.querySelector(".modal-product__btn--wishlist")};function q(){a.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden",window.addEventListener("keydown",h),a.modal.addEventListener("click",L)}function g(){a.modal.classList.remove("modal--is-open"),document.body.style.overflow="",window.removeEventListener("keydown",h),a.modal.removeEventListener("click",L)}function h(t){t.code==="Escape"&&g()}function L(t){t.target===t.currentTarget&&g(),console.log(t.target)}d.defaults.baseURL=T;async function M(){const{data:t}=await d.get(i.CATEGORIES);return t}async function _(t=1){const e=(t-1)*12,{data:o}=await d.get(`${i.PRODUCTS}?limit=${l}&skip=${e}`);return o}async function R(t,e){const o=(e-1)*12,{data:c}=await d.get(`${i.CATEGORY}${t}?limit=${l}&skip=${o}`);return c}async function A(t){const{data:e}=await d.get(`${i.PRODUCT_BY_ID}${t}`);return e}async function B(t,e=1){const o=(e-1)*12,{data:c}=await d.get(i.SEARCH_PRODUCT,{params:{q:t,limit:l,skip:o}});return c}function O(t){const e=t.map(o=>`
<li class="categories__item">
   <button class="categories__btn" type="button">${o}</button>
 </li>
`).join("");a.listCategories.innerHTML=e}function m(t){const e=t.map(({id:o,category:c,thumbnail:r,title:n,brand:p,price:f})=>`
    <li class="products__item" data-id="${o}">
    <img class="products__image" src="${r}" alt="${n}"/>
    <p class="products__title">${n}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${p}</span></p>
    <p class="products__category">Category: ${c}</p>
    <p class="products__price">Price: ${f}</p>
 </li>
`).join("");a.listProducts.insertAdjacentHTML("beforeend",e)}function b(){a.loadMore.classList.remove("is-hidden")}function C(){a.loadMore.classList.remove("is-hidden")}function E(){a.loader.classList.add("is-hidden")}function P(){a.loader.classList.add("is-hidden")}function D(){a.listProducts.innerHTML=""}function u(){a.notFound.classList.add("not-found--visible")}function y(){a.notFound.classList.remove("not-found--visible")}function U({id:t,category:e,brand:o,title:c,thumbnail:r,price:n,tags:p,description:f,shippingInformation:$,returnPolicy:w}){const S=p.map(v=>`${v}`).join(""),k=`<img class="modal-product__img" src="${r}" alt="${c}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${c}</p>
        <ul class="modal-product__tags">${S}</ul>
        <p class="modal-product__description">${f}</p>
        <p class="modal-product__shipping-information">Shipping: ${$}</p>
        <p class="modal-product__return-policy">Return Policy: ${w}</p>
        <p class="modal-product__price">Price:${n} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;a.modalProduct.innerHTML=k}let s=1;async function H(){try{y(),C(),E();const t=await M();console.log(t);const e=["All",...t];O(e),document.querySelector(".categories__btn").classList.add("categories__btn--active");const{products:o,total:c,skip:r}=await _(s);o.length>0?(m(o),c-r-l>0&&b()):u()}catch(t){console.log(t)}finally{P()}}async function I(t){if(t.target.nodeName!=="BUTTON")return;const e=t.target.textContent;document.querySelectorAll(".categories__btn").forEach(o=>{o.classList.remove("categories__btn--active")}),t.target.classList.add("categories__btn--active");try{y(),C(),E(),D(),console.log(e),s=1;let o;const{products:c,total:r,skip:n}=e==="All"?await _(s):await R(e,s);c.length>0?(m(c),r-n-l>0&&b()):u()}catch(o){console.log(o.message)}finally{P()}}async function N(t){if(t.target.parentElement.nodeName!=="LI")return;let e=t.target.parentElement.dataset.id;try{const o=await A(e);console.log(o),o&&(q(),U(o))}catch(o){alert(o.message)}}async function F(t){t.preventDefault(),a.listProducts.innerHTML="";const e=t.target.elements.searchValue.value.trim();if(console.log(e),!e){u();return}try{const o=await B(e,s=1);if(console.log(o),o.products.length===0){u();return}y(),m(o.products)}catch(o){alert(o.message)}finally{t.target.reset()}}async function j(){a.form.reset();try{const t=await _(s);m(t.products)}catch(t){alert(t.message)}}document.addEventListener("DOMContentLoaded",H);a.listCategories.addEventListener("click",I);a.listProducts.addEventListener("click",N);a.modalCloseBtn.addEventListener("click",g);a.form.addEventListener("submit",F);a.formClearBtn.addEventListener("click",j);
//# sourceMappingURL=index.js.map
