export default {
  listCategories: document.querySelector('.categories'),
  listProducts: document.querySelector('.products'),
  loadMore: document.querySelector('.load-more-btn'),
  loader: document.querySelector('.loader'),
  notFound: document.querySelector('.not-found'),
  modal: document.querySelector('.modal'),
  modalProduct: document.querySelector('.modal-product'),
  modalCloseBtn: document.querySelector('.modal__close-btn'),
  form: document.querySelector('.search-form'),
  formClearBtn: document.querySelector('.search-form__btn-clear'),
  notFound: document.querySelector('.not-found'),
  modalAddToCart: document.querySelector('.modal-product__btn--cart'),
  modalWishlistCart: document.querySelector('.modal-product__btn--wishlist'),
  cartCount: document.querySelector('[data-cart-count]'),
  wishlistCount: document.querySelector('[data-wishlist-count]'),
};
